on: [push]

jobs:
    lint:
        name: RunMake
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all
            - name: Create artifact data
              run:
                echo "Make is succesfully completed." > ./make_artifact.txt
            - name: Save Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Make Artifact
                path: ./make_artifact.txt            
    test:
        needs: [lint]	
        name: RunTest
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: Make Artifact
                path: ./make_artifact.txt 
            - name: Read artifact
              run:
                echo "Make Artifact:" && cat ./make_artifact.txt 
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all							
            - name: Test
              run: ./test
    build:
        name: RunPackage 
        needs: [test]
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all							
            - uses: jiro4989/build-deb-action@v4
              with:
               package: RWO
               package_root: package
               maintainer: Dokotas
               version: 1.0 # refs/tags/v*.*.*
               arch: 'amd64' # optional
               depends: 'libc6 (>= 2.2.1), git' # optional
               desc: 'this is sample package.' # optional
               homepage: 'https://github.com/Dokotas/Reverse-Words-Order' # optional      			
