on: [push]

jobs:
    lint:
        name: RunMake
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all
            - name: Create artifact data
              run:
                echo "Make is succesfully completed." > ./make_artifact.txt
            - name: Save Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Make Artifact
                path: ./make_artifact.txt            
    test:
        needs: [lint]	
        name: RunTest
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: Make Artifact
                path: ./
            - name: Read artifact
              run:
                echo "Make Artifact:" && cat ./make_artifact.txt 
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all							
            - name: Test
              run: ./test
            - name: Create artifact data
              run:
                ./test > ./test_artifact.txt
            - name: Save Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Test Artifact
                path: ./test_artifact.txt    
    build:
        name: RunPackage 
        needs: [test]
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: Test Artifact
                path: ./
            - name: Read artifact
              run:
                echo "Test Artifact:" && cat ./test_artifact.txt               
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all							
            - uses: jiro4989/build-deb-action@v4
              with:
               package: RWO
               package_root: package
               maintainer: Dokotas
               version: 1.0 # refs/tags/v*.*.*
               arch: 'amd64' # optional
               depends: 'libc6 (>= 2.2.1), git' # optional
               desc: 'this is sample package.' # optional
               homepage: 'https://github.com/Dokotas/Reverse-Words-Order' # optional  
    build-docker:
        name: RunDocker
        needs: [build]
        runs-on: self-hosted
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: dokotas
                password: ${{ secrets.DOCKERHUB_TOKEN }}              
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3    
            - name: Build and push
              uses: docker/build-push-action@v6      
              with:
                push: true
                tags: dokotas/reverse-words-order
                secrets: GIT_AUTH_TOKEN=${{ secrets.TOKEN }}
