name: Python packaging

on: [push]

jobs:
    lint:
        name: RunMake
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all
    test:
        needs: [lint]	
        name: RunTest
        runs-on: self-hosted
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: make
              run: make all
            - name: make test
              run: make -f TestMakefile all							
            - name: Test
              run: ./test